# Generated by Django 4.2.28 on 2026-02-23 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to='agents.agent')),
                ('triggered_by_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_referrer_bonuses', to='agents.agent')),
                ('triggered_by_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to='clients.client')),
            ],
            options={
                'db_table': 'referral_bonuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewAgentBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_agent_bonuses', to='agents.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_agent_bonuses', to='clients.client')),
            ],
            options={
                'db_table': 'new_agent_bonuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='referralbonus',
            constraint=models.UniqueConstraint(fields=('referrer', 'deal_number'), name='unique_referrer_deal_number'),
        ),
        migrations.AddConstraint(
            model_name='newagentbonus',
            constraint=models.UniqueConstraint(fields=('agent', 'deal_number'), name='unique_agent_deal_number'),
        ),
    ]
