# Generated by Django 4.2.28 on 2026-02-23 06:36

import agents.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('agent_type', models.CharField(blank=True, choices=[('RE_BROKER', 'RE Broker'), ('MORTGAGE_BROKER', 'Mortgage Broker'), ('OTHER', 'Other')], default='', max_length=20)),
                ('agent_type_other', models.CharField(blank=True, default='', max_length=255)),
                ('rera_number', models.CharField(blank=True, default='', max_length=50)),
                ('agent_code', models.CharField(default=agents.models.generate_agent_code, max_length=20, unique=True)),
                ('device_token', models.CharField(blank=True, default='', max_length=255)),
                ('is_whatsapp_business', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('has_completed_first_action', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_agents', to='agents.agent')),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
