# Generated by Django 4.2.28 on 2026-02-23 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('referral_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_whatsapp_business', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('device_token', models.CharField(blank=True, default='', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
            ],
            options={
                'db_table': 'whatsapp_sessions',
            },
        ),
    ]
