# Generated by Django 4.2.28 on 2026-02-23 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=20)),
                ('expected_mortgage_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed')], default='SUBMITTED', max_length=20)),
                ('channel', models.CharField(default='PARTNER_PWA', max_length=50)),
                ('consent_given', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='agents.agent')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
