# Generated by Django 4.2.28 on 2026-02-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='crm_lead_id',
            field=models.UUIDField(blank=True, help_text='Lead ID from Rivo CRM', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(
                choices=[
                    ('SUBMITTED', 'Submitted'),
                    ('CONTACTED', 'Contacted'),
                    ('QUALIFIED', 'Qualified'),
                    ('SUBMITTED_TO_BANK', 'Submitted to Bank'),
                    ('PREAPPROVED', 'Preapproved'),
                    ('FOL_RECEIVED', 'FOL Received'),
                    ('DISBURSED', 'Disbursed'),
                    ('DECLINED', 'Declined'),
                ],
                default='SUBMITTED',
                max_length=20,
            ),
        ),
    ]
