# Generated by Django 4.2.28 on 2026-02-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_whatsappsession'),
        ('clients', '0002_client_crm_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='source_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='agents.agent'),
        ),
    ]
